[package]
name = "vidhan-site"
version = "0.1.0"
edition = "2021"
authors = ["Vidhan Bhatt <me@vidhan.io>"]
license = "AGPL-3.0"
publish = false

[dependencies]
axum = { version = "0.6", features = ["macros", "tracing"] }
axum-extra = "0.7.7"
color-eyre = "0.6"
envy = "0.4"
futures-util = { version = "0.3", features = ["std"], default-features = false }
html-escape = "0.2.13"
html-node = { version = "0.2", features = ["axum"] }
hyper = "0.14"
once_cell = "1.18.0"
pulldown-cmark = { git = "https://github.com/raphlinus/pulldown-cmark" }
regex = "1.9.3"
request-id = { version = "0.2", features = ["ulid"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.25"
thiserror = "1"
time = { version = "0.3.26", features = [
    "macros",
    "serde",
    "serde-human-readable",
] }
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tower = "0.4"
tower-http = { version = "0.4", features = [
    "cors",
    "fs",
    "request-id",
    "trace",
    "util",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tree-sitter = "0.20"
tree-sitter-highlight = "0.20"
tree-sitter-html = "0.19.0"
tree-sitter-java = "0.20.0"
tree-sitter-rust = "0.20"
